### ISSUE TITLE
Remove dependency on curl and make

### ISSUE THREAD

**Issue by Flamefire** [ax3l/cmake-easyinstall#2]
`curl` is listed as a dependency but not used.

Instead of relying on `make` you can use `cmake --build` which works with any generator. Newer cmake version even have `cmake --install` but for now you can use `cmake --build . --target install --config=Release` (or so)

**Comment by ax3l** [comment]
True that, `curl` is actually only needed to install the tool itself in an automated manner ^^

Are you aware how to limit the number of cores with `cmake --build`?
Update: oh, CMake 3.12 has `-j|--parallel <jobs>` it seams: https://stackoverflow.com/a/50883555/2719194
